import Link from "next/link";
import { ArrowRight, ArrowUpRight, Check, ChevronDown, FileCheck2, Link2, Network, ScanLine, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PlanCards } from "@/components/billing/plan-cards";
import { SynoloBrand, SynoloMark } from "@/components/synolo-brand";
import { MarketingHeader, MarketingHero, FeatureExplorer } from "./landing-interactive";
import { FAQ, OFFICE_POINTS } from "./landing-content";

function OfficeSection() {
  return <section className="synolo-office-section" id="logistes"><div className="synolo-container"><div className="synolo-office-grid"><div><p className="synolo-eyebrow">ΓΙΑ ΛΟΓΙΣΤΙΚΑ ΓΡΑΦΕΙΑ</p><h2 className="synolo-section-kicker">Η ίδια εικόνα.<br />Χωρίς τα πήγαινε-έλα.</h2><p className="synolo-section-statement">Πολλοί πελάτες.<br /><em>Μία καθαρή προτεραιότητα.</em></p><p className="synolo-section-description">Το γραφείο σας δεν είναι ένας ακόμη χρήστης της επιχείρησης. Έχει το δικό του περιβάλλον, για να οργανώνει πελάτες, βιβλία και συνεργάτες.</p><Button asChild className="synolo-button-light mt-7" data-testid="office-register-cta"><Link href="/accountant-signup">Δημιουργήστε το γραφείο σας <ArrowUpRight className="size-4" /></Link></Button></div><div className="synolo-office-points" data-testid="office-features-card">{OFFICE_POINTS.map((p, i) => <article key={p.title} data-testid={`office-benefit-${i}`}><p.icon className="size-5" /><div><h3>{p.title}</h3><p>{p.text}</p></div></article>)}</div></div><div className="synolo-connect-strip" data-testid="connect-accountant-steps"><span>ΣΥΝΔΕΘΕΙΤΕ ΟΠΩΣ ΣΑΣ ΒΟΛΕΥΕΙ</span><p><Check className="size-4" /> Κωδικός συνεργασίας</p><p><Check className="size-4" /> Αίτημα με ΑΦΜ</p><p><Check className="size-4" /> Πρόσκληση με email</p></div></div></section>;
}

function Differentiators() {
  return <section className="synolo-section synolo-container" id="symmorfosi"><div className="synolo-section-intro"><p className="synolo-eyebrow">ΛΙΓΟΤΕΡΗ ΤΡΙΒΗ. ΠΕΡΙΣΣΟΤΕΡΗ ΟΥΣΙΑ.</p><h2 className="synolo-section-kicker">Τα εργαλεία είναι πολλά. Η διαφορά είναι πώς συνεργάζονται.</h2><p className="synolo-section-statement">Δεν προσθέτουμε απλώς οθόνες.<br /><em>Συνδέουμε τη δουλειά.</em></p></div><div className="synolo-difference-grid" data-testid="mydata-bento-grid"><article className="synolo-ai-card" data-testid="landing-ai-feature"><Sparkles className="size-6" /><p className="synolo-mini-label">AI ΜΕΣΑ ΣΤΗ ΡΟΗ ΕΡΓΑΣΙΑΣ</p><h3>Προτείνει την κίνηση.<br />Εσείς κρατάτε το τιμόνι.</h3><p>Από την αναγνώριση μιας απόδειξης μέχρι την προτεινόμενη υπενθύμιση πληρωμής, ο βοηθός βρίσκεται εκεί που γίνεται η δουλειά.</p><div className="synolo-ai-example"><span>Εσείς</span><p>«Ποιος χρειάζεται υπενθύμιση πληρωμής;»</p><div><Sparkles className="size-4" /><span>Ανάλυση υπολοίπων → προτεινόμενο μήνυμα → δική σας έγκριση</span></div></div></article><div className="synolo-difference-stack"><article data-testid="landing-control-feature"><FileCheck2 className="size-5" /><h3>Ο έλεγχος πριν από την έκπληξη.</h3><p>Εκκρεμή myDATA, αποκλίσεις Φ2, προθεσμίες και έλεγχοι βιβλίων σε οργανωμένη εικόνα — όχι κρυμμένα σε διαφορετικά αρχεία.</p></article><article data-testid="landing-import-feature"><ScanLine className="size-5" /><h3>Αλλάζετε εργαλείο. Όχι αφετηρία.</h3><p>Οδηγός εισαγωγής CSV από Excel ή Elorus, με αντιστοίχιση στηλών και προεπισκόπηση. Κρατήστε την ιστορία της δουλειάς σας.</p></article></div></div></section>;
}

function EcosystemSection() {
  return <section className="synolo-ecosystem" id="gefyres"><div className="synolo-container synolo-ecosystem-grid"><div><p className="synolo-eyebrow">ΠΑΡΟΧΟΙ + ΛΟΓΙΣΤΙΚΕΣ ΓΕΦΥΡΕΣ</p><h2 className="synolo-section-kicker">Ένα οικοσύστημα, όχι ένα κλειστό κουτί.</h2><p className="synolo-section-statement">Η επιλογή του εργαλείου σας<br /><em>δεν πρέπει να σας περιορίζει.</em></p><p className="synolo-section-description">Ηλεκτρονική τιμολόγηση, B2G και λογιστική επικοινωνία αποτελούν κομμάτια του ίδιου συνόλου. Συνδέσεις παρόχων, εξαγωγές δεδομένων και API χτίζουν τη συνέχεια ανάμεσα στα συστήματά σας.</p><div className="synolo-ecosystem-notes"><div><Link2 className="size-5" /><p><strong>Δική μας υπηρεσία παρόχου. Ανοιχτή διασύνδεση.</strong><span>Εξελίσσουμε το Σύνολο με δική μας υπηρεσία ηλεκτρονικής τιμολόγησης, παράλληλα με συνδέσεις σε άλλους παρόχους.</span></p></div><div><Network className="size-5" /><p><strong>Γέφυρες με όλο το λογιστικό οικοσύστημα.</strong><span>Στόχος μας είναι η σύνδεση με όλα τα υπάρχοντα λογιστικά προγράμματα, βάσει των προδιαγραφών κάθε εφαρμογής.</span></p></div></div><p className="synolo-small-note" data-testid="ecosystem-availability-note">Η ενεργοποίηση κάθε διασύνδεσης εξαρτάται από την υποστήριξη, την παραμετροποίηση και τους όρους του αντίστοιχου συστήματος.</p></div><div className="synolo-ecosystem-map" aria-label="Το οικοσύστημα του Σύνολο ERP" data-testid="ecosystem-diagram"><div className="synolo-ecosystem-hub"><SynoloMark className="size-12" /><strong>Σύνολο ERP</strong><span>Η βάση της συνεργασίας σας</span></div><div className="synolo-map-spokes"><div>Ηλεκτρονική τιμολόγηση<span>myDATA · B2G · Πάροχοι</span></div><div>Λογιστικά προγράμματα<span>Γέφυρες · Εξαγωγές · Βιβλία</span></div><div>Εμπορικό οικοσύστημα<span>Πληρωμές · e-shop · API</span></div><div>Επιχείρηση & γραφείο<span>Κοινά δεδομένα · Δικαιώματα</span></div></div></div></div></section>;
}

function PricingAndFaq() {
  return <><section className="synolo-section synolo-container" id="timologisi" data-testid="pricing-section"><div className="synolo-section-intro"><p className="synolo-eyebrow">ΧΩΡΟΣ ΝΑ ΜΕΓΑΛΩΣΕΤΕ</p><h2 className="synolo-section-kicker">Ξεκινήστε με αυτό που χρειάζεστε.</h2><p className="synolo-section-statement">Το δικό σας μέγεθος.<br /><em>Το δικό σας Σύνολο.</em></p><p className="synolo-section-description">14 ημέρες δωρεάν δοκιμή, χωρίς κάρτα. Επιλέξτε το πακέτο με τις δυνατότητες και τα όρια που ταιριάζουν στη δουλειά σας.</p></div><div className="synolo-pricing"><PlanCards mode="marketing" /></div><p className="synolo-small-note">Οι τιμές δεν περιλαμβάνουν ΦΠΑ. Οι υπηρεσίες τρίτων διέπονται από τους αντίστοιχους όρους.</p></section><section className="synolo-faq synolo-container" id="faq"><div><p className="synolo-eyebrow">ΚΑΘΑΡΕΣ ΑΠΑΝΤΗΣΕΙΣ</p><h2 className="synolo-section-kicker">Πριν ξεκινήσετε.</h2><p className="synolo-section-statement">Λογικές ερωτήσεις.<br /><em>Χωρίς ψιλά γράμματα.</em></p></div><div className="synolo-faq-list" data-testid="faq-accordion">{FAQ.map((f, i) => <details key={f.q} data-testid={`faq-item-${i}`}><summary data-testid={`faq-question-${i}`}>{f.q}<ChevronDown className="size-4 shrink-0" /></summary><p data-testid={`faq-answer-${i}`}>{f.a}</p></details>)}</div></section></>;
}

export function SynoloLanding() {
  return <div className="synolo-public synolo-landing" data-testid="synolo-landing"><a className="synolo-skip-link" href="#main-content" data-testid="landing-skip-link">Μετάβαση στο περιεχόμενο</a><MarketingHeader /><main id="main-content"><MarketingHero /><Differentiators /><section className="synolo-features-section" id="epixeiriseis"><div className="synolo-container"><div className="synolo-section-intro"><p className="synolo-eyebrow">ΟΛΕΣ ΟΙ ΠΛΕΥΡΕΣ ΤΗΣ ΔΟΥΛΕΙΑΣ ΣΑΣ</p><h2 className="synolo-section-kicker">Δυνατότητες με λόγο ύπαρξης.</h2><p className="synolo-section-statement">Κάθε εργαλείο λύνει κάτι.<br /><em>Μαζί, αλλάζουν την καθημερινότητα.</em></p></div><FeatureExplorer /></div></section><OfficeSection /><EcosystemSection /><PricingAndFaq /><section className="synolo-final-cta"><div className="synolo-container"><SynoloMark className="size-12" /><div><p className="synolo-eyebrow">Η ΕΠΟΜΕΝΗ ΜΕΡΑ ΤΗΣ ΔΟΥΛΕΙΑΣ ΣΑΣ</p><p className="synolo-section-statement">Ας τα βάλουμε σε ένα Σύνολο.</p></div><Button asChild size="lg" className="synolo-button" data-testid="landing-final-register"><Link href="/register">Ξεκινήστε τη δοκιμή σας <ArrowRight className="size-4" /></Link></Button></div></section></main><footer className="synolo-footer"><div className="synolo-container"><Link href="/" data-testid="footer-brand-link"><SynoloBrand compact /></Link><p>Εμπορική διαχείριση και λογιστικό γραφείο. Μαζί.</p><nav aria-label="Νομικά και πρόσβαση"><Link href="/terms" data-testid="footer-terms">Όροι χρήσης</Link><Link href="/privacy" data-testid="footer-privacy">Απόρρητο</Link><Link href="/portal" data-testid="footer-portal">Πύλη πελάτη</Link><Link href="/login" data-testid="footer-login">Σύνδεση</Link></nav></div></footer></div>;
}
