"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowDown, ArrowRight, Building2, Check, ChevronRight, Menu, X, Sparkles, BookOpen, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { SynoloBrand, SynoloMark } from "@/components/synolo-brand";
import { FEATURES, FEATURE_GROUPS } from "./landing-content";

const NAV = [["epixeiriseis", "Δυνατότητες"], ["logistes", "Για λογιστές"], ["gefyres", "Πάροχοι & γέφυρες"], ["timologisi", "Πακέτα"], ["faq", "Ερωτήσεις"]];

export function MarketingHeader() {
  const [open, setOpen] = useState(false);
  return <header className="synolo-header"><div className="synolo-container synolo-header-inner">
    <Link href="/" className="synolo-brand-link" aria-label="Σύνολο ERP — αρχική" data-testid="nav-brand-logo"><SynoloBrand /></Link>
    <nav className="synolo-desktop-nav" aria-label="Κύρια πλοήγηση">{NAV.map(([id, text]) => <a key={id} href={`#${id}`} data-testid={`nav-link-${id}`}>{text}</a>)}</nav>
    <div className="flex items-center gap-2"><Button asChild variant="ghost" className="synolo-nav-login" data-testid="nav-login-link"><Link href="/login">Σύνδεση</Link></Button><Button asChild className="synolo-button synolo-nav-register" data-testid="nav-register-link"><Link href="/register">Δωρεάν δοκιμή <ArrowRight className="size-4" /></Link></Button><button className="synolo-menu-toggle" aria-label={open ? "Κλείσιμο μενού" : "Άνοιγμα μενού"} aria-expanded={open} aria-controls="marketing-mobile-nav" onClick={() => setOpen(!open)} data-testid="landing-mobile-menu">{open ? <X /> : <Menu />}</button></div>
  </div>{open && <nav id="marketing-mobile-nav" className="synolo-mobile-nav" aria-label="Πλοήγηση κινητού" data-testid="landing-mobile-navigation">{NAV.map(([id, text]) => <a key={id} href={`#${id}`} onClick={() => setOpen(false)} data-testid={`mobile-nav-${id}`}>{text}<ChevronRight className="size-4" /></a>)}<Link href="/register" onClick={() => setOpen(false)} data-testid="mobile-nav-register">Ξεκινήστε δωρεάν <ArrowRight className="size-4" /></Link></nav>}</header>;
}

function ProductPreview({ office }: { office: boolean }) {
  const rows = office ? [["Έλεγχος βιβλίων", "Φ2 & myDATA", "Για έλεγχο"], ["Οργάνωση ομάδας", "Πελάτες & αναθέσεις", "Σε εξέλιξη"], ["Έγγραφα πελατών", "Αιτήματα & αρχεία", "Συγκεντρωμένα"]] : [["Παραστατικό πελάτη", "Πώληση & myDATA", "Εκδόθηκε"], ["Είσπραξη πελάτη", "Τράπεζα & αντιστοίχιση", "Αντιστοιχίστηκε"], ["Εικόνα βιβλίων", "Συνεργασία με λογιστή", "Για έλεγχο"]];
  return <figure className="synolo-preview" data-testid="hero-product-preview"><div className="synolo-preview-top"><SynoloMark className="size-6 text-[#23645d]" /><span>Σύνολο / {office ? "Γραφείο" : "Επιχείρηση"}</span><span className="synolo-preview-dot" /></div><div className="synolo-preview-body"><div className="flex items-start justify-between gap-3"><div><p className="synolo-mini-label">Η ΔΟΥΛΕΙΑ ΣΑΣ, ΣΥΝΔΕΔΕΜΕΝΗ</p><p className="synolo-preview-title">{office ? "Κάθε πελάτης. Στη θέση του." : "Μια πιο καθαρή εικόνα."}</p></div><span className="synolo-preview-icon">{office ? <BookOpen className="size-5" /> : <Building2 className="size-5" />}</span></div><div className="synolo-preview-metrics"><div><span>{office ? "Πελάτες" : "Πωλήσεις"}</span><strong>{office ? "Μία εικόνα" : "Οργανωμένες"}</strong></div><div><span>{office ? "Προτεραιότητες" : "Εισπράξεις"}</span><strong>{office ? "Ξεκάθαρες" : "Υπό έλεγχο"}</strong></div><div><span>{office ? "Συνεργασία" : "Λογιστής"}</span><strong>Συνδεδεμένα</strong></div></div><div className="synolo-flow-line">{["Καταχώρηση", "Έλεγχος", "Εικόνα"].map((label, i) => <span key={label}><span className="synolo-flow-node">{i < 2 ? <Check className="size-3" /> : "3"}</span>{label}</span>)}</div><div className="synolo-preview-rows">{rows.map(([title, subtitle, status], i) => <div key={title} className="synolo-preview-row"><span className="synolo-row-number">0{i + 1}</span><div><strong>{title}</strong><span>{subtitle}</span></div><span className={`synolo-row-status ${i === 2 ? "is-amber" : ""}`}>{status}</span></div>)}</div><div className="synolo-assistant-note"><Sparkles className="size-4 shrink-0" /><span>{office ? "Το AI βοηθά να βάλετε προτεραιότητες." : "Οι προτάσεις γίνονται ενέργειες με τον έλεγχό σας."}</span></div></div><figcaption>Ενδεικτική απεικόνιση της ροής εργασίας</figcaption></figure>;
}

export function MarketingHero() {
  const [office, setOffice] = useState(false);
  return <section className="synolo-hero"><div className="synolo-container synolo-hero-grid"><div className="synolo-hero-copy synolo-enter"><p className="synolo-eyebrow"><span /> ΕΠΙΧΕΙΡΗΣΗ + ΛΟΓΙΣΤΙΚΟ ΓΡΑΦΕΙΟ</p><h1 data-testid="landing-hero-title">Η επιχείρησή σας.<br />Το λογιστήριό σας.<br /><em>Ένα Σύνολο.</em></h1><p className="synolo-hero-description">Από την πρώτη πώληση μέχρι την εικόνα των βιβλίων σας. Τιμολόγηση, χρήματα, αποθήκη και συνεργασία — σε ένα σύστημα που συνδέει τη δουλειά σας.</p><div className="synolo-hero-actions"><Button asChild size="lg" className="synolo-button" data-testid="hero-primary-cta"><Link href="/register?type=business">Ξεκινήστε δωρεάν <ArrowRight className="size-4" /></Link></Button><a href="#epixeiriseis" className="synolo-text-link" data-testid="hero-explore-features">Γνωρίστε το Σύνολο <ArrowDown className="size-4" /></a></div><p className="synolo-trial-note"><Check className="size-3.5" />14 ημέρες δοκιμή <span>·</span> Χωρίς κάρτα</p><Link href="/accountant-signup" className="synolo-office-link" data-testid="hero-accountant-cta">Έχετε λογιστικό γραφείο; <span>Αυτή είναι η δική σας πλευρά <ArrowRight className="size-3.5" /></span></Link></div><div className="synolo-hero-visual synolo-enter"><div className="synolo-persona-switch" role="group" aria-label="Προεπισκόπηση περιβάλλοντος"><button type="button" aria-pressed={!office} onClick={() => setOffice(false)} data-testid="door-business-button"><Building2 className="size-4" /> Επιχείρηση</button><button type="button" aria-pressed={office} onClick={() => setOffice(true)} data-testid="door-accountant-button"><BookOpen className="size-4" /> Λογιστικό γραφείο</button></div><ProductPreview office={office} /><div className="synolo-connection-note"><ShieldCheck className="size-4" /><span>Δύο περιβάλλοντα. Κοινά δεδομένα. Δικά σας δικαιώματα.</span></div></div></div><div className="synolo-container synolo-capability-strip" data-testid="landing-capability-strip"><span>ΟΧΙ ΑΛΛΟ ΕΝΑ ΕΡΓΑΛΕΙΟ ΤΙΜΟΛΟΓΗΣΗΣ</span><p>myDATA <b>+</b> B2G <b>+</b> Εμπορική διαχείριση <b>+</b> AI <b>+</b> Λογιστική</p></div></section>;
}

export function FeatureExplorer() {
  const [group, setGroup] = useState("all");
  const features = FEATURES.filter((f) => group === "all" || f.group === group);
  return <><div className="synolo-feature-tabs" role="group" aria-label="Φίλτρο δυνατοτήτων" data-testid="feature-category-filters">{FEATURE_GROUPS.map((g) => <button type="button" key={g.id} aria-pressed={group === g.id} onClick={() => setGroup(g.id)} data-testid={`feature-filter-${g.id}`}>{g.label}</button>)}</div><p className="sr-only" role="status" data-testid="feature-result-count">{features.length} δυνατότητες</p><div className="synolo-feature-grid" data-testid="business-features-grid">{features.map((f) => <article className="synolo-feature" key={f.id} data-testid={`feature-${f.id}`}><div className="synolo-feature-label"><f.icon className="size-4" /><span>{f.title}</span></div><h3>{f.slogan}</h3><p>{f.text}</p></article>)}</div></>;
}
