import Link from "next/link";
import { ArrowLeft, Check, Layers, LockKeyhole, Sparkles } from "lucide-react";
import { SynoloBrand } from "@/components/synolo-brand";

export function AuthShell({ title, description, children, footer, wide, audience = "business" }: { title: string; description?: string; children: React.ReactNode; footer?: React.ReactNode; wide?: boolean; audience?: "business" | "office" }) {
  const office = audience === "office";
  return <div className="synolo-public synolo-auth" data-testid="synolo-auth-shell">
    <aside className="synolo-auth-story"><Link href="/" className="synolo-brand-link" data-testid="auth-desktop-brand"><SynoloBrand /></Link><div className="synolo-auth-story-content"><p className="synolo-eyebrow">{office ? "Η ΔΙΚΗ ΣΑΣ ΠΛΕΥΡΑ ΤΟΥ ΣΥΝΟΛΟΥ" : "Η ΔΟΥΛΕΙΑ ΣΑΣ, ΣΥΝΔΕΔΕΜΕΝΗ"}</p><p className="synolo-auth-story-statement">{office ? <>Πολλοί πελάτες.<br />Μία εικόνα.<br /><em>Το δικό σας γραφείο.</em></> : <>Λιγότερα πήγαινε-έλα.<br /><em>Περισσότερο Σύνολο.</em></>}</p><p className="synolo-auth-story-description">{office ? "Το γραφείο, οι συνεργάτες και οι πελάτες σας στο ίδιο πλαίσιο εργασίας. Με σαφείς προτεραιότητες και δικό σας έλεγχο." : "Τιμολόγηση, εισπράξεις και καθημερινή διαχείριση. Μαζί με τον λογιστή σας, όχι σε παράλληλους κόσμους."}</p><div className="synolo-auth-benefits"><div><Layers className="size-4" /><span>{office ? "Ξεχωριστή πύλη για όλους τους πελάτες σας" : "Από το παραστατικό στην εικόνα των βιβλίων"}</span></div><div><Sparkles className="size-4" /><span>Έξυπνες προτάσεις εκεί που γίνεται η δουλειά</span></div><div><Check className="size-4" /><span>Συνεργασία με καθορισμένα δικαιώματα</span></div></div></div><p className="synolo-auth-story-footer">Εμπορική διαχείριση και λογιστικό γραφείο. Μαζί.</p></aside>
    <main className="synolo-auth-main"><div className="synolo-auth-topline"><Link href="/" className="synolo-auth-mobile-brand" data-testid="auth-mobile-brand"><SynoloBrand compact /></Link><Link href="/" className="synolo-auth-back" data-testid="auth-back-home"><ArrowLeft className="size-3.5" /> Πίσω στην αρχική</Link></div><div className={`synolo-auth-card ${wide ? "is-wide" : ""}`}><h1 data-testid="auth-page-title">{title}</h1>{description && <p className="synolo-auth-description" data-testid="auth-page-description">{description}</p>}<div className="synolo-auth-form-body">{children}</div>{footer && <div className="synolo-auth-footer">{footer}</div>}</div><footer className="synolo-auth-legal"><span className="inline-flex items-center gap-1.5"><LockKeyhole className="size-3" /> Η πρόσβαση ανήκει σε εσάς</span><Link href="/terms" data-testid="auth-legal-terms">Όροι χρήσης</Link><Link href="/privacy" data-testid="auth-legal-privacy">Απόρρητο</Link></footer></main>
  </div>;
}
